### ISSUE TITLE
Drop `quick-validation.yml` (importable) workflow

### ISSUE THREAD

**Issue by atc0005** [atc0005/shared-project-resources#63]
## Overview

This workflow *only* triggers for pushes to a branch made directly by me (due to repo permissions), or to the primary branch of a repo once merged via a Pull Request.

The workflows that trigger on PR submission already cover the steps provided by this workflow and I'm continuing to invest time in streamlining those workflows, so having this one that finishes by the time the PR is first opened isn't as helpful as it once was.

I'm going to phase it out in two steps:

- drop valid entries from the workflow and wire it up to trigger CI failures whenever it is called by a dependent project
- drop the file entirely once I'm confident that I've removed all references to it

## TODO

- [x] atc0005/bounce
- [x] atc0005/brick
- [x] atc0005/bridge
- [x] atc0005/check-cert
- [x] atc0005/check-illiad
- [x] atc0005/check-mail
- [x] atc0005/check-ntpt
- [x] atc0005/check-path
- [x] atc0005/check-process
- [x] atc0005/check-restart
- [x] atc0005/check-statuspage
- [x] atc0005/check-vmware
- [x] atc0005/check-whois
- [x] atc0005/dnsc
- [x] atc0005/elbow
- [x] atc0005/go-ezproxy
- [x] atc0005/go-lockss
- [x] atc0005/mysql2sqlite
- [x] atc0005/go-nagios
- [x] atc0005/go-teams-notify
- [x] atc0005/nagios-debug
- [x] atc0005/query-meta
- [x] atc0005/safelinks
- [x] atc0005/send2teams
- [x] atc0005/tsm-pass

**Comment by atc0005** [comment]
https://github.com/atc0005/check-cert/actions/runs/4185876120/jobs/7253564507

![image](https://user-images.githubusercontent.com/36716992/219086619-b0e4abec-7497-4109-a106-1c85cad1f176.png)

The changes work as expected.

Since (AFAIK) I'm the only user of the workflow no real harm/aggravation is caused by using this approach to phasing out the workflow. But on the off-chance that someone else *is* using it, the link back to this GH issue helps provide explanation other than the importable workflow simply vanishing.

**Comment by atc0005** [comment]
Workflow removed from dependent project. About to drop the `quick-validation.yml` workflow file.
