### ISSUE TITLE
Restore `on.push` hook to `Project Analysis` workflow to resolve CodeQL scanning warnings

### ISSUE THREAD

**Issue by atc0005** [atc0005/shared-project-resources#86]
## Overview

Work performed previously to rework workflow scheduling batched several changes together:

- add scheduled-weekly.yml
- add scheduled-monthly.yml
- update project-analysis.yml
  - remove schedule
  - remove "on push"
  - apply jobs for PRs against ANY branch

The `remove "on push"` change caused issues with the `Vulnerability / CodeQL` job:

> 1 issue was detected with this workflow: Please specify an on.push hook so that Code Scanning can compare pull requests against the state of the base branch.

refs: https://github.com/atc0005/check-restart/actions/runs/4447435792

I attempted to [add the "on push" hook at the shared/importable workflows level](https://github.com/atc0005/shared-project-resources/pull/85), but that does not appear to have resolved the issue. Instead, it looks like I'll need to batch restore the `on.push` hook to all dependent projects so that the `Vulnerability / CodeQL` job can execute as intended.

A side effect of the change is that this will result in the other analysis jobs also running when changes are merged to the primary branch, but the overall CI cost shouldn't be *too* great. If it is, we can refactor so that the CodeQL workflow job resides within a dedicated workflow file.

## TODO

- [ ] atc0005/bounce
- [ ] atc0005/brick
- [ ] atc0005/bridge
- [ ] atc0005/check-cert
- [ ] atc0005/check-illiad
- [ ] atc0005/check-mail
- [ ] atc0005/check-ntpt
- [ ] atc0005/check-path
- [ ] atc0005/check-process
- [ ] atc0005/check-restart
- [ ] atc0005/check-statuspage
- [ ] atc0005/check-vmware
- [ ] atc0005/check-whois
- [ ] atc0005/dnsc
- [ ] atc0005/elbow
- [ ] atc0005/go-ci
- [ ] atc0005/go-ezproxy
- [ ] atc0005/go-lockss
- [ ] atc0005/mysql2sqlite
- [ ] atc0005/go-nagios
- [ ] atc0005/go-teams-notify
- [ ] atc0005/nagios-debug
- [ ] atc0005/query-meta
- [ ] atc0005/safelinks
- [ ] atc0005/send2teams
- [ ] atc0005/tsm-pass
